name: Trackers Away

on:
  push:
    branches:
      - 'master'
      - 'e-builder'
      - 'dev'
      - 'action'

jobs:
  test:
    name: test on ubuntu
    strategy:
      matrix:
        node-version: [12.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: do a test
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CI: true
        run: |
          echo 'token has been set'
          yarn
          yarn test


  deploy:
    name: Deploy
    strategy:
      matrix:
        node-version: [12.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    needs: test
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: do a deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CI: true
        run: |
          echo 'token has been set'
          yarn
          yarn build
